# Generated by Django 6.1.1 on 2026-09-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_menuitem_image_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='tagline',
            field=models.CharField(blank=True, help_text='A short, evocative line about this restaurant', max_length=200),
        ),
    ]
